config/routes.rb
Rails.application.routes.draw do
  get 'archive' => 'archive#index', as: :archive_index
  resources :entries
  root to: "entries#index"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :calories, :proteins, :carbohydrates, :fats, :meal_type, presence: true

  def day
    self.created_at.strftime('%b %e, %Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archive_controller.rb
class ArchiveController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archive_helper.rb
module ArchiveHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archive/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">
                Entries for <%= day %>
            </h3>
            <div class="level py-6">
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Calories</p>
                        <p class="title"><%= entries.pluck(:calories).sum %></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Proteins</p>
                        <p class="title"><%= entries.pluck(:proteins).sum %></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Carbohydrates</p>
                        <p class="title"><%= entries.pluck(:carbohydrates).sum %></p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Fats</p>
                        <p class="title"><%= entries.pluck(:fats).sum %></p>
                    </div>
                </div>
            </div>

            <% entries.each do |entry| %>
                <%= link_to entry do %>
                    <div class="card">
                        <div class="card-content">
                            <strong><%= entry.meal_type %></strong><br />

                            <%= entry.calories %> calories,
                            <%= entry.proteins %> proteins,
                            <%= entry.carbohydrates %> carbohydrates,
                            <%= entry.fats %> fats,
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/entries/_entry.html.erb
<div class="card column" id="<%= dom_id entry %>" style="max-width: 400px; width: 100%">
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><%= entry.meal_type %></p>
        <p class="subtitle is-6"><%= time_ago_in_words entry.created_at %> ago</p>
      </div>
    </div>
    <div class="content">
      <p>
        <strong>Calories</strong>: <%= entry.calories %>
      </p>
      <p>
        <strong>Proteins</strong>: <%= entry.proteins %>
      </p>
      <p>
        <strong>Carbohydrates</strong>: <%= entry.carbohydrates %>
      </p>
      <p>
        <strong>Fats</strong>: <%= entry.fats %>
      </p>
    </div>
  </div>
    <footer class="card-footer">
      <%= link_to "Show", entry, { class: "card-footer-item" } %>
      <%= link_to "Edit", edit_entry_path(entry), { class: "card-footer-item" } %>
      <%= link_to "Delete", entry, data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' }, class: 'card-footer-item' %>
    </footer>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, class: "box", html: { style: "max-width: 800px" }) do |form| %>
  <% if entry.errors.any? %>
    <div class="message">
      <div class="message-header has-background-danger">
        <p class=""><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body has-background-danger-light" >
        <% entry.errors.each do |error| %>
          <p class="has-text-weight-semibold has-text-danger"><%= error.full_message %></p>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="columns is-multiline">  
    <div class="field column is-half">
      <%= form.label :meal_type, style: "display: block", class: "label" %>
      <div class="control">
        <%= form.text_field :meal_type, placeholder: "Meal type", class: "input" %>
      </div>
    </div>

    <div class="field column is-half">
      <%= form.label :calories, style: "display: block", class: "label" %>
      <div class="control">
        <%= form.number_field :calories, class: 'input' %>
      </div>
    </div>
    <div class="field column is-half">
      <%= form.label :proteins, style: "display: block", class: "label" %>
      <div class="control">
        <%= form.number_field :proteins, class: 'input' %>
      </div>
    </div>

    <div class="field column is-half">
      <%= form.label :carbohydrates, style: "display: block", class: "label" %>
      <div class="control">
      <%= form.number_field :carbohydrates, class: "input" %>
      </div>
    </div>

    <div class="field column is-half">
      <%= form.label :fats, style: "display: block", class: "label" %>
      <div class="control">
      <%= form.number_field :fats, class: "input" %>
      </div>
    </div>
  </div>
  <div class="field">
    <%= form.submit class: "button is-link" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1 class="title is-4 has-text-link has-text-weight-bold">Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div class="field is-grouped">
  <div class="control">  
      <%= link_to "Show this entry", @entry, class: "button is-link" %>
  </div>
  <div>
    <%= link_to "Back to entries", entries_path, class: "button" %>
  </div>
</div>

app/views/entries/index.html.erb
<div id="entries" class="columns mt-6 is-variable is-3 is-multiline" style="width: 100%;gap: 32px">
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
</div>

<%= link_to "All entries", :archive_index, class: "button is-link is-outlined mt-6 is-centered" %>

app/views/entries/new.html.erb
<h1 class="title is-4 has-text-link has-text-weight-bold">New entry</h1>

<%= render "form", entry: @entry %>

<br>

<%= link_to "Back to entries", entries_path, class: "button" %>

app/views/entries/show.html.erb
<%= render @entry %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyFoodLog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/header"%>

    <% if notice.present? %>
      <p id="notice" class="notification is-link is-light"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p id="notice" class="notification is-danger is-light"><%= notice %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "FoodLog", :root, { class: 'navbar-item has-text-weight-semibold has-text-link is-size-3' } %>
    <a class="navbar-item" href="https://bulma.io">
      
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <%= link_to "Create new Entry", :new_entry, { class: 'button is-primary has-text-weight-bold' } %>
        </div>
      </div>
    </div>
  </div>
</nav>